services:
  app:
    container_name: "landing"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 3001:3000
    networks:
      - proxy

networks:
  proxy:
    external: true