services:
  landing-website:
    image: "ghcr.io/vivite-project/landing-website:main"
    restart: always
    environment:
      - NODE_ENV=production
    deploy:
      mode: replicated
      replicas: 2
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - proxy

networks:
  proxy:
    external: true