services:
  landing-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vivite-landing:staging
    environment:
      - NODE_ENV=production
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 1
