name: Rebuild and Restart Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [build]
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_HOST }}
          cd ${{ secrets.PROJECT_PATH }}
          git pull origin main
          docker-compose down
          docker-compose up -d --build
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
