name: Rebuild and Restart Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        
      - name: Deploy to remote server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          TARGET: ${{ secrets.TARGET }}
          SCRIPT_BEFORE: "docker compose down"
          SCRIPT_AFTER: "docker compose up --build -d"
